### ISSUE TITLE
else

### ISSUE THREAD

**Issue by sudahiroshi** [Ren-Sekiya/research#19]
ifと独立してelseStatementが存在していますが，ifStatementの中に入れてください．
ifが重なっている場合の階層の判断はパーサの方でお願いします．

色々簡略化して書くと以下のような感じです．

```
"type": "ifStatement",
"condition": { 中略 },
"block": { 中略 },
"else": { 中略 }
```

**Comment by Ren-Sekiya** [comment]
if,if-else if, if- else, if-else if-elseを作るのかも
